// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Ly1E8O0EOW-kuwQV3JHtL7xgzjPQ854',
    appId: '1:830851525853:android:1532d5a377cf53af4c3f34',
    messagingSenderId: '830851525853',
    projectId: 'chatapp-2ae46',
    storageBucket: 'chatapp-2ae46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClPIoAg6AyHpmjd8Md1OxWMX9btV3t0Es',
    appId: '1:830851525853:ios:f316142950e5e3bf4c3f34',
    messagingSenderId: '830851525853',
    projectId: 'chatapp-2ae46',
    storageBucket: 'chatapp-2ae46.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMVsd1wKluMxnmr7XxDGdLoNTHFahDyoI',
    appId: '1:830851525853:web:179c71010d439c594c3f34',
    messagingSenderId: '830851525853',
    projectId: 'chatapp-2ae46',
    authDomain: 'chatapp-2ae46.firebaseapp.com',
    storageBucket: 'chatapp-2ae46.firebasestorage.app',
  );

}